name: temp
channels:
- defaults
- conda-forge
dependencies:
- python=3.7
- pip
- jupyter
- conda
- scipy
- pandas
- numpy
- matplotlib=3.1.1
- pip:
  - autopep8
  - pylint
  - rope
  - jupyter_contrib_nbextensions
  - scikit-learn==0.22.1
  - streamlit==0.57